x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"

x-backend-app-environment: &x-backend-app-environment
  APP_NAME: "pmserver"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "8080"
  DB_URL: "postgresql://user:password@db:5432/db?sslmode=disable"

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me
  app:
    container_name: app
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - app.lvh.me

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - nginx.lvh.me

networks:
  app_network:
    external: false

volumes:
  db_data:
